version: '3.3'
services:

  app:
    image: hltspires/stonks-bot
    build: .
    networks:
      - stonks-bot

  db:
    image: hltspires/stonks-db
    build:
      ./database
    environment:
      - POSTGRES_USER=stonks
      - POSTGRES_PASSWORD=stonks
      - POSTGRES_DB=stonks
    volumes:
      - ${HOME}/stonks-db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - stonks-bot

networks:
  stonks-bot: